# Generated by Django 3.0.4 on 2020-03-12 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('music_file', models.FileField(upload_to='')),
                ('music_name', models.CharField(max_length=50)),
                ('extension', models.CharField(default='mp3', editable=False, max_length=10)),
                ('is_being_played', models.BooleanField(default=False)),
            ],
        ),
    ]
