# Generated by Django 3.0.4 on 2020-03-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='music_size',
            field=models.IntegerField(default=0),
        ),
    ]
